name_max_length: 50
pw_min_length: 6
email_max_length: 255
gravatar_size: 50
gravatar_size2: 80
per_page: 6
per_page_word: 15
category_name_min_length: 6
category_des_min_length: 10
number_of_answer: 4
